### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by christian-draeger**
to make clear how multiple parameters are passed to wiremock. took me a while and a dive into the code to figure it out

### CODE REVIEW

**Comment by automatictester** [comment]
Hi @christian-draeger, many thanks for your interest in improving the documentation! Would you mind adding it to both examples of pom.xml in readme?
To be honest I never needed to specify both http and https while working with WireMock. Is this something you actually had to do? If not, would you mind replacing the second param with something more usual, e.g. `--verbose`?

**Comment by christian-draeger** [comment]
hey, 
yes in my case i needed `--port=8089 --https-port=8090 --global-response-templating` but `--verbose` would be ok for the readme as well. my intention is basically showing how to set multiple parameters.

i will update the readme

**Comment by christian-draeger** [comment]
added `--verbose` to both examples of pom.xml in readme

**Comment by automatictester** [comment]
Many thanks for contributing.

**Pull request merged**
